import type { Property, Scenario, JourneyPhase, UserProfile } from "./property-types"

export const sampleProperties: Property[] = [
  {
    id: "prop-1",
    address: "1247 Maple Street",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    price: 485000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1850,
    lotSize: "0.25 acres",
    yearBuilt: 2018,
    propertyType: "Single Family",
    imageUrl: "/placeholder.svg?height=300&width=400",
    listingDate: "2024-01-15",
    daysOnMarket: 12,
    mlsNumber: "ATX-2024-001",
    description:
      "Beautiful modern home in sought-after South Austin neighborhood. Open floor plan with updated kitchen, hardwood floors throughout, and large backyard perfect for entertaining.",
    features: ["Hardwood Floors", "Updated Kitchen", "Large Backyard", "Two-Car Garage", "Walk-in Closets"],
    neighborhood: "South Austin",
    schoolDistrict: "Austin ISD",
    hoaFees: 0,
    propertyTaxRate: 0.0181,
    estimatedInsurance: 1800,
    walkScore: 78,
    commuteTime: "25 min to downtown",
    nearbyAmenities: ["Zilker Park", "South Lamar", "Whole Foods", "Austin FC Stadium"],
  },
  {
    id: "prop-2",
    address: "892 Oak Avenue",
    city: "Austin",
    state: "TX",
    zipCode: "78745",
    price: 425000,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1650,
    lotSize: "0.18 acres",
    yearBuilt: 2015,
    propertyType: "Townhouse",
    imageUrl: "/placeholder.svg?height=300&width=400",
    listingDate: "2024-01-10",
    daysOnMarket: 17,
    mlsNumber: "ATX-2024-002",
    description:
      "Stylish townhouse in growing neighborhood. Low maintenance living with modern amenities and close to major employers. Perfect for first-time buyers.",
    features: ["Open Floor Plan", "Granite Counters", "Stainless Appliances", "Covered Patio", "Master Suite"],
    neighborhood: "Southeast Austin",
    schoolDistrict: "Austin ISD",
    hoaFees: 185,
    propertyTaxRate: 0.0181,
    estimatedInsurance: 1500,
    walkScore: 65,
    commuteTime: "20 min to downtown",
    nearbyAmenities: ["McKinney Falls", "Austin-Bergstrom Airport", "The DOMAIN", "Mueller District"],
  },
  {
    id: "prop-3",
    address: "2156 Cedar Lane",
    city: "Austin",
    state: "TX",
    zipCode: "78731",
    price: 675000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    lotSize: "0.35 acres",
    yearBuilt: 2020,
    propertyType: "Single Family",
    imageUrl: "/placeholder.svg?height=300&width=400",
    listingDate: "2024-01-08",
    daysOnMarket: 19,
    mlsNumber: "ATX-2024-003",
    description:
      "Stunning new construction in prestigious Northwest Hills. Premium finishes throughout, gourmet kitchen, and resort-style backyard. Top-rated schools nearby.",
    features: ["Gourmet Kitchen", "Quartz Countertops", "Smart Home Features", "Pool", "Three-Car Garage"],
    neighborhood: "Northwest Hills",
    schoolDistrict: "Eanes ISD",
    hoaFees: 0,
    propertyTaxRate: 0.0181,
    estimatedInsurance: 2200,
    walkScore: 45,
    commuteTime: "30 min to downtown",
    nearbyAmenities: ["Lake Austin", "Hill Country Galleria", "Top Golf", "Eanes Elementary"],
  },
  {
    id: "prop-4",
    address: "445 Riverside Drive",
    city: "Austin",
    state: "TX",
    zipCode: "78741",
    price: 395000,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    lotSize: "N/A",
    yearBuilt: 2019,
    propertyType: "Condo",
    imageUrl: "/placeholder.svg?height=300&width=400",
    listingDate: "2024-01-12",
    daysOnMarket: 15,
    mlsNumber: "ATX-2024-004",
    description:
      "Contemporary condo with river views. Building amenities include fitness center, rooftop deck, and concierge. Walking distance to downtown and entertainment districts.",
    features: ["River Views", "Balcony", "In-Unit Laundry", "Fitness Center", "Rooftop Deck"],
    neighborhood: "East Austin",
    schoolDistrict: "Austin ISD",
    hoaFees: 425,
    propertyTaxRate: 0.0181,
    estimatedInsurance: 800,
    walkScore: 92,
    commuteTime: "10 min to downtown",
    nearbyAmenities: ["Lady Bird Lake", "Rainey Street", "Convention Center", "East 6th Street"],
  },
]

export const defaultScenarios: Scenario[] = [
  {
    id: "current",
    name: "Home Base",
    description: "National average starting point — 30% housing, 20% down",
    active: true,
    financialInputs: {
      annualIncome: 125000,
      monthlyExpenses: 2600,
      fixedDebts: 520,
      downPaymentSources: 55000,
      creditScore: 720,
      interestRate: 7.0,
      loanTerm: 30,
      housingPercentage: 30,
      downPaymentPercentage: 20,
      marketReferenceRate: 7.0,
    },
  },
  {
    id: "after-promotion",
    name: "NYC",
    description: "Moving to New York City",
    active: false,
    financialInputs: {
      annualIncome: 180000,
      monthlyExpenses: 4200,
      fixedDebts: 580,
      downPaymentSources: 43000,
      creditScore: 740,
      interestRate: 6.85,
      loanTerm: 30,
    },
  },
]

export const initialJourneyPhases: JourneyPhase[] = [
  {
    id: "discover",
    name: "Discover Homes",
    description: "Exploring options and narrowing possibilities",
    color: "#028090",
    completed: false,
    properties: ["prop-1", "prop-2", "prop-3", "prop-4"],
  },
  {
    id: "deep-sense",
    name: "Get Deep Sense",
    description: "Learning more about potential homes",
    color: "#2b6cb0",
    completed: false,
    properties: [],
  },
  {
    id: "offer-strategy",
    name: "Know What to Offer",
    description: "Preparing and evaluating offers",
    color: "#1a365d",
    completed: false,
    properties: [],
  },
]

export const defaultUserProfile: UserProfile = {
  id: "user-1",
  name: "Dale & Jamie",
  scenarios: defaultScenarios,
  activeScenarioId: "current",
  journeyPhases: initialJourneyPhases,
  savedProperties: [],
  preferences: {
    maxPrice: 500000,
    minBedrooms: 2,
    preferredAreas: ["South Austin", "East Austin", "Central Austin"],
    mustHaveFeatures: ["Updated Kitchen", "Parking"],
    dealBreakers: ["HOA > $300", "Major Repairs Needed"],
  },
}
